import type {
  Experience,
  Profile,
  Project,
  SkillCategory,
} from "./types";

export const fallbackProfile: Profile = {
  name: "Md. Rabiul Hassan Mahmud",
  initials: "RA",
  title: "Senior Software Developer & Architect",
  tagline:
    "15+ years crafting robust, scalable software. From startup MVPs to enterprise systems — I turn complex problems into elegant solutions.",
  roles: [
    "Full-Stack Developer",
    "Software Architect",
    "Backend Engineer",
    "Tech Lead",
  ],
  location: "London, UK",
  email: "hassanmahmud.sa@gmail.com",
  availability: "Open to new opportunities",
  responseTime: "Within 24 hours",
  summary: [
    "I'm a passionate software developer with over 15 years of experience designing and building scalable web applications, APIs, and distributed systems. I thrive at the intersection of clean architecture and pragmatic delivery.",
    "Throughout my career I've worn many hats — from individual contributor to tech lead — guiding teams across fintech, e-commerce, and SaaS. I care deeply about code quality, developer experience, and shipping products that actually make a difference.",
    "When I'm not coding, I'm mentoring junior developers, contributing to open source, or exploring the latest advancements in cloud-native and AI-assisted development.",
  ],
  stats: [
    { value: "15+", label: "Years Experience" },
    { value: "80+", label: "Projects Shipped" },
    { value: "30+", label: "Happy Clients" },
    { value: "London", label: "Based In" },
  ],
  socials: [
    {
      label: "GitHub",
      value: "github.com/khassanmahmud",
      href: "https://github.com",
    },
    {
      label: "LinkedIn",
      value: "linkedin.com/in/khassanmahmud",
      href: "https://linkedin.com",
    },
  ],
};

export const fallbackSkillCategories: SkillCategory[] = [
  {
    title: "Frontend",
    color: "from-blue-500 to-cyan-500",
    skills: [
      { name: "React / Next.js", level: 96 },
      { name: "TypeScript", level: 94 },
      { name: "Tailwind CSS", level: 92 },
      { name: "Vue.js", level: 82 },
    ],
  },
  {
    title: "Backend",
    color: "from-indigo-500 to-violet-500",
    skills: [
      { name: "Node.js", level: 97 },
      { name: "Python / Django", level: 88 },
      { name: "Go", level: 80 },
      { name: "Java / Spring", level: 78 },
    ],
  },
  {
    title: "Data & Infra",
    color: "from-violet-500 to-purple-500",
    skills: [
      { name: "PostgreSQL / MySQL", level: 92 },
      { name: "Redis / Elasticsearch", level: 85 },
      { name: "MongoDB", level: 83 },
      { name: "AWS / GCP", level: 88 },
    ],
  },
  {
    title: "DevOps & Tools",
    color: "from-purple-500 to-pink-500",
    skills: [
      { name: "Docker / Kubernetes", level: 87 },
      { name: "CI/CD (GitHub Actions)", level: 90 },
      { name: "Terraform / IaC", level: 80 },
      { name: "Linux / Bash", level: 93 },
    ],
  },
];

export const fallbackTechBadges: string[] = [
  "React",
  "Next.js",
  "TypeScript",
  "Node.js",
  "Python",
  "Go",
  "Java",
  "PostgreSQL",
  "Redis",
  "MongoDB",
  "AWS",
  "GCP",
  "Docker",
  "Kubernetes",
  "GraphQL",
  "REST APIs",
  "Terraform",
  "CI/CD",
  "Microservices",
  "gRPC",
  "WebSockets",
  "Kafka",
  "Redis Streams",
  "Nginx",
  "Linux",
];

export const fallbackExperiences: Experience[] = [
  {
    id: "senior-project-manager-bjit-inc",
    role: "Senior Project Manager",
    company: "BJIT Inc",
    url: "#",
    period: "2023 — Present",
    type: "Full-time",
    description:
      "Leading architecture and delivery of a multi-tenant SaaS platform serving 2M+ users. Drove migration from monolith to microservices, reducing deployment time by 70% and infrastructure cost by 40%.",
    highlights: [
      "Designed event-driven architecture using Kafka & Kubernetes",
      "Mentored a team of 8 engineers across 3 time zones",
      "Reduced API latency by 60% through caching and query optimization",
    ],
    tech: ["Node.js", "React", "Kubernetes", "AWS", "Kafka", "PostgreSQL"],
    accent: "from-indigo-500 to-violet-500",
  },
  {
    id: "principal-software-engineer-bjit-ltd",
    role: "Principal Software Engineer",
    company: "BJIT Ltd",
    url: "#",
    period: "2022 — 2023",
    type: "Full-time",
    description:
      "Built core banking APIs and real-time payment processing systems handling £5M+ daily transactions. Ensured PCI-DSS compliance and 99.99% uptime SLA.",
    highlights: [
      "Engineered high-throughput payment pipeline processing 10k TPS",
      "Led OAuth 2.0 / OpenID Connect identity platform rollout",
      "Introduced automated testing, raising coverage from 20% to 85%",
    ],
    tech: ["Java", "Spring Boot", "PostgreSQL", "Redis", "AWS", "Docker"],
    accent: "from-violet-500 to-purple-500",
  },
  {
    id: "senior-software-engineer-bjit-ltd",
    role: "Senior Software Engineer",
    company: "BJIT Ltd",
    url: "#",
    period: "2018 — 2022",
    type: "Full-time",
    description:
      "Developed full-stack features for a high-traffic retail platform with 500k daily visitors. Owned search, recommendation engine, and checkout optimizations.",
    highlights: [
      "Integrated SRE (Speech Recognition) API into a web app for targeting the Japanese people.",
      "Developed a music blog for a Japanese client.",
      "Worked in QR based payment method used in Japan for Japanese vending machines.",
      "Developed a railway information website for targeting the audience who are aiming to visit Japan.",
      "Optimized performance of an e-commerce site by 30%  targeting the Japanese market.",
      "Migrated Javascript React project to Typescript React to support TypeScript features.",
    ],
    tech: ["PHP", "Laravel", "Vue.js", "MySQL", "Elasticsearch", "Redis"],
    accent: "from-purple-500 to-pink-500",
  },
  {
    id: "software-engineer-ambala-it",
    role: "Software Engineer",
    company: "Ambala IT",
    url: "#",
    period: "2016 — 2018",
    type: "Full-time",
    description:
      "Started my professional journey building CMS-driven websites and internal tools for SMB clients. Gained solid foundations in web standards, accessibility, and agile delivery.",
    highlights: [
      "Technical leader of software development team consists of 7 members.",
      "Lead ERP and Micro Finance software development team since 2015.",
      "Developing an ERP large scale software including 5 modules (Inventory, FAMS – Fixed Asset Management System, Procurement, HR and Payroll and Accounting).",
      "Developing Micro Finance software for NGO.",
      "Managing server with Linux Cent OS.",
    ],
    tech: ["PHP", "WordPress", "jQuery", "MySQL", "HTML/CSS"],
    accent: "from-pink-500 to-rose-500",
  },
  {
    id: "software-engineer-orange-bd",
    role: "Software Engineer",
    company: "Orange BD",
    url: "#",
    period: "2012 — 2015",
    type: "Full-time",
    description:
      "Started my professional journey building CMS-driven websites and internal tools for SMB clients. Gained solid foundations in web standards, accessibility, and agile delivery.",
    highlights: [
      "Website Development using WordPress and custom CMS.",
      "Software and Web Application Development by using PHP, MySQL, JavaScript, jQuery, AJAX, JSON.",
      "Customized Web Application.",
      "Lead a team of Quality Control (QC) as a Head of QC.",
      "Lead a team of Junior Software Engineer.",
      "Supervise an Oursourcing Department for the proper guidance and the individual development.",
    ],
    tech: ["PHP", "WordPress", "jQuery", "MySQL", "HTML/CSS"],
    accent: "from-pink-500 to-rose-500",
  },
  {
    id: "programmer-software-address",
    role: "Programmer",
    company: "Software Address",
    url: "#",
    period: "2012 — 2012",
    type: "Full-time",
    description:
      "Started my professional journey building CMS-driven websites and internal tools for SMB clients. Gained solid foundations in web standards, accessibility, and agile delivery.",
    highlights: [
      "PSD to HTML conversion.",
      "HTML to WordPress conversion.",
      "Custom Software Development using PHP and MySQL.",
      "Website and Blog Development using WordPress.",
      "Website Development using Joomla, Drupal.",
      "Website Redesign and Maintenance.",
      "Customized Web Application.",
    ],
    tech: ["PHP", "WordPress", "jQuery", "MySQL", "HTML/CSS"],
    accent: "from-pink-500 to-rose-500",
  },
  {
    id: "web-developer-untitled-it-solutions",
    role: "Web Developer",
    company: "Untitled IT Solutions",
    url: "#",
    period: "2011 — 2011",
    type: "Full-time",
    description:
      "Started my professional journey building CMS-driven websites and internal tools for SMB clients. Gained solid foundations in web standards, accessibility, and agile delivery.",
    highlights: [
      "PSD to HTML conversion.",
      "HTML to WordPress conversion.",
      "Website and Blog Development using WordPress.",
      "Customization and Modification of WordPress and WordPress plugins.",
      "Website Redesign and Maintenance.",
      "Customized Web Application.",
    ],
    tech: ["PHP", "WordPress", "jQuery", "MySQL", "HTML/CSS"],
    accent: "from-pink-500 to-rose-500",
  },
];

export const fallbackProjects: Project[] = [
  {
    id: "cloudpay-gateway",
    title: "CloudPay Gateway",
    description:
      "High-throughput payment processing platform handling £5M+ daily transactions. Built with event-driven architecture for reliability and horizontal scalability.",
    image: null,
    tags: ["Node.js", "Kafka", "PostgreSQL", "Redis", "Docker"],
    github: "#",
    live: "#",
    featured: true,
    gradient: "from-indigo-600/20 via-violet-600/10 to-transparent",
    accent: "indigo",
  },
  {
    id: "devcollab-saas",
    title: "DevCollab SaaS",
    description:
      "Real-time collaborative development environment with live code sharing, integrated CI/CD pipelines, and AI-assisted code review.",
    image: null,
    tags: ["Next.js", "WebSockets", "Go", "Kubernetes", "AWS"],
    github: "#",
    live: "#",
    featured: true,
    gradient: "from-violet-600/20 via-purple-600/10 to-transparent",
    accent: "violet",
  },
  {
    id: "analyticsforge",
    title: "AnalyticsForge",
    description:
      "Data analytics dashboard built for enterprise clients. Ingests millions of events per day with sub-second query responses via smart caching layers.",
    image: null,
    tags: ["React", "D3.js", "Python", "ClickHouse", "Redis"],
    github: "#",
    live: "#",
    featured: false,
    gradient: "from-purple-600/20 via-pink-600/10 to-transparent",
    accent: "purple",
  },
  {
    id: "openauth",
    title: "OpenAuth",
    description:
      "Open-source OAuth 2.0 / OpenID Connect identity server with PKCE, MFA, and social login support. 1.2k GitHub stars.",
    image: null,
    tags: ["Go", "JWT", "PostgreSQL", "Docker"],
    github: "#",
    live: "#",
    featured: false,
    gradient: "from-pink-600/20 via-rose-600/10 to-transparent",
    accent: "pink",
    stars: 1200,
  },
  {
    id: "shopstream",
    title: "ShopStream",
    description:
      "Headless e-commerce engine with real-time inventory, AI product recommendations, and Stripe checkout integration.",
    image: null,
    tags: ["Next.js", "Stripe", "Elasticsearch", "Prisma"],
    github: "#",
    live: "#",
    featured: false,
    gradient: "from-blue-600/20 via-cyan-600/10 to-transparent",
    accent: "blue",
  },
  {
    id: "infrakit-cli",
    title: "InfraKit CLI",
    description:
      "Developer-friendly CLI tool for scaffolding cloud-native infrastructure using Terraform and Helm. Used by 500+ developers.",
    image: null,
    tags: ["Go", "Terraform", "Helm", "Kubernetes", "AWS"],
    github: "#",
    live: "#",
    featured: false,
    gradient: "from-cyan-600/20 via-teal-600/10 to-transparent",
    accent: "cyan",
  },
];
